[versions]
agp = "8.5.0"
kotlin = "2.0.0"
ksp = "2.0.0-1.0.22"
room = "2.6.1"
coreKtx = "1.7.0"
appcompat = "1.6.1"
material = "1.11.0"
junit = "4.13.2"
ktor = "2.3.7"
datastore = "1.1.1"
divkit = "30.9.0"
mockk = "1.13.12"
mockwebserver = "4.12.0"
yandexAuthsdk = "3.1.0"
kotlinxSerializationJson = "1.7.1"

[libraries]
agp = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-kapt-gradle-plugin = { group = "org.jetbrains.kotlin.kapt", name = "org.jetbrains.kotlin.kapt.gradle.plugin", version.ref = "kotlin" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

yandex-div = { group = "com.yandex.div", name = "div", version.ref = "divkit" }
yandex-div-core = { group = "com.yandex.div", name = "div-core", version.ref = "divkit" }
yandex-div-json = { group = "com.yandex.div", name = "div-json", version.ref = "divkit" }
yandex-div-picasso = { group = "com.yandex.div", name = "picasso", version.ref = "divkit" }
yandex-auth-sdk = { group = "com.yandex.android", name = "authsdk", version.ref = "yandexAuthsdk" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref="mockwebserver" }
androidx-junit = { group = "androidx.test.ext", name = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name="com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
compose-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
androidx-datastore= { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

ktor-client = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }